Q5. Create a function that converts a word to a bitstring and then to a boolean list based on the following criteria:

    1. Locate the position of the letter in the English alphabet (from 1 to 26).
    2. Odd positions will be represented as 1 and 0 otherwise.
    3. Convert the represented positions to boolean values, 1 for True and 0 for False.
    4. Store the conversions into an array.

 Examples

to_boolean_list("deep") ➞ [False, True, True, False]
# deep converts to 0110
# d is the 4th alphabet - 0
# e is the 5th alphabet - 1
# e is the 5th alphabet - 1
# p is the 16th alphabet - 0

to_boolean_list("loves") ➞ [False, True, False, True, True]

to_boolean_list("tesh") ➞ [False, True, True, False]


In [1]:
import logging
import numpy as np
logging.basicConfig(filename = "Assignment1.log", level = logging.INFO, 
                     format = '%(asctime)s %(levelname)s %(message)s')


In [2]:
def position(s):
    try:
        if(s.upper()):
            s.casefold()
        p = ord(s) - 96
        return p
    except Exception as e:
        raise Exception("ques-5 failed")

In [3]:
def oddeven(s):
    try:
        if(s % 2 != 0):
            return True
        else:
            return False

    except Exception as e:
        raise Exception("ques-5 failed")
        

In [4]:
def bools(s):
    try:
        if(s == 1):
            return True
        else:
            return False

    except Exception as e:
        raise Exception("ques-5 failed")


In [5]:
def to_boolean_list(s):
    try:
        l = []
        for i in s:
            a = position(i)
            a = oddeven(a)
            a = bools(a)
            l.append(a)
        
        ans = np.array(l)
        logging.info("Ques-5 executed succesfully")
        return ans

    except Exception as e:
        logging.exception("exception occured in Ques-5 " + str(e))
        raise Exception("ques-5 failed")


In [6]:
to_boolean_list("deep")

array([False,  True,  True, False])

In [7]:
to_boolean_list("iNeuron")

array([ True, False,  True,  True, False,  True, False])

In [8]:
to_boolean_list("ABCDEfghijklMNOPQrstuvWXYZ")

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False])